### ISSUE TITLE
Zeige die Kategorie einer Frage im ACP an

### ISSUE THREAD

**Issue by TitusKirch** [tkirchDev/dev.tkirch.wsc.faq#27]

**Comment by azerusDE** [comment]
Ich habe für meinen Anwendungsfall die Standard-Filter in der ACP-Übersicht eingebaut und in der Übersicht auch die hier im Issue genannten Kategorien. Wenn Interesse besteht, kann ich das gern als PR umsetzen.

<img width="908" alt="Bildschirmfoto 2020-06-14 um 17 16 57" src="https://user-images.githubusercontent.com/1836347/84597231-de6dfe80-ae62-11ea-876d-e7daf04c5fd5.png">

**Comment by TitusKirch** [comment]
Das ist ein grandioser Lösungsvorschlag (ich habe tatsächlich nur an eine extra Spalte gedacht).
Wenn du dafür einen PR (mit dem Ziel "next") stellen würdest, wäre das echt klasse^^
