### ISSUE TITLE
BBCode has no content

### ISSUE THREAD

**Issue by TitusKirch** [tkirchDev/dev.tkirch.wsc.faq#30]
Editor:
![image](https://user-images.githubusercontent.com/16943133/84654592-c3a59380-af0f-11ea-907c-8d8a4230b07d.png)

Result:
![image](https://user-images.githubusercontent.com/16943133/84654639-d28c4600-af0f-11ea-9744-46423bdd5ebb.png)

Forum:
https://tkirch.dev/forum/thread/192-bbcode-zeigt-nichts-mehr-an/?postID=1057#post1057

**Comment by Hanashi** [comment]
Behoben durch #36
