### ISSUE TITLE
File attachments are not loaded 

### ISSUE THREAD

**Issue by TitusKirch** [tkirchDev/dev.tkirch.wsc.faq#39]
File attachments are not loaded (they are displayed only as a link)

![unknown (1)](https://user-images.githubusercontent.com/16943133/103238856-44782a00-494c-11eb-961a-e194ef26d3ec.png)

**Comment by TitusKirch** [comment]
See https://github.com/HanashiDev/dev.hanashi.wsc.wysiwyg-i18n-form/issues/1

**Comment by Hanashi** [comment]
I will check this.

**Comment by Hanashi** [comment]
Ich habe mir das jetzt genau angeschaut. Ich bekomme es nicht hin. Ich weiß nicht woran das liegt.

**Comment by Hanashi** [comment]
Ich habe mir das jetzt genau angeschaut. Ich bekomme es nicht hin. Ich weiß nicht woran das liegt.
