### ISSUE TITLE
Improve frontend FAQ question list page layout

### ISSUE THREAD

**Issue by Krymonota** [tkirchDev/dev.tkirch.wsc.faq#60]
The layout of the frontend FAQ list page can be improved in several ways:

- Semantic improvements
    - Use `h2` instead of `h1` for FAQ category titles
    - Use a `div` instead of `header` element for FAQ questions
- Visual improvements
    - Add borders and padding for better grouping by eye*
- Functional improvements / fixes
    - Enable toggling of questions in sub categories
- Technical improvements
    - Reduce duplicate question container code by moving template code to a separate template file
    - Reduce dependency on jQuery and improve code readibility by switching to plain JavaScript

\* 
![New FAQ question list page layout](https://user-images.githubusercontent.com/12609161/163711054-a560c00c-5e8f-483a-894f-34b0f64a06b7.png)

**Comment by TitusKirch** [comment]
This would also close #19 at the same time

**Comment by Krymonota** [comment]
> This would also close #19 at the same time

Ooops, I didn't see the other issue. Yup, thanks for mentioning!
